credit_score/urls.py
from django.contrib import admin
from django.urls import path,include
from score import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dbconnect/',include('score.urls')),


    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 

]



score/urls.py

from django.urls import path
from . import views
#from .views import GeneratePDF


urlpatterns = [
    path('cust_id/',views.cust_id),
    path('cust_id/test/', views.test,name='test'),#Calling  cust_id function to test function 
    path('database/',views.process),
    path('database/add/',views.add,name='add'),



    # path('emp/', views.emp),  
    # path('show/',views.show),  
    # path('emp/edit/<int:id>', views.edit),  
    # path('emp/update/<int:id>', views.update),  
    # path('emp/delete/<int:id>', views.destroy), 



    #path('credit_score/',views.credit_result,name='credit_result')
    #path('cust_id/pdf/',GeneratePDF.as_view(),name='GeneratePDF'),
]



score/models.py
from django.db import models  
class Employee(models.Model):
    #id = models.BigAutoField(primary_key=True)  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee"  

score/forms.py
from django import forms  
from score.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

score/views.py
#https://www.javatpoint.com/django-crud-applicationS

import json
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from jinja2 import Environment, FileSystemLoader
#from weasyprint import HTML

# Create your views here.
#from django.db import connection
from pandas.core.indexes.base import Index

#from score.test_sql_3 import *

#Creata the function for enter the customer_id 
def cust_id(request):
     return render(request,'score/cust_id.html')


# def test(request):
#     val1=int(request.GET['num1'])
#     json_Value=(sql_value(val1))

#     print(json_Value)
#     print(type(json_Value))
#     value=JsonResponse(sql_value(),safe=False)
#     print(type(value))
#     return value
 
    #return render(request,'score/test.html',{'json_Value':json_Value})
    #return HttpResponse(json_Value)
    #return JsonResponse(sql_value(),safe=False)
    #return ("Hellow world")




from django.db import connection

def process(request):
    #json_Value=(sql_value())
    # print(json_Value)
    # print(type(json_Value))
    #value=JsonResponse(json_Value,safe=False)
    # print(type(value))
    return render(request,'score/test1.html')#,{'json_Value':json_Value})
    # value_dict=json.loads(str(value))
    # print(type(value_dict))
    #return HttpResponse("hellow world")
  

from score.credit_score_model_making import *
def add(request):
    val1=int(request.GET['num1'])
    val2=int(request.GET['num2'])
    new=displayText(val1,val2)
    # res= val1+val2
    return render(request,'score/result.html',{'result':new})




from django.test import TestCase
from django.http import HttpResponse
from django.template.loader import get_template
from .pdf_converter import render_to_pdf
from django.views.generic import View
from score.credit_score_prediction_file import *

# Create your tests here.
def test(request):
    #template = get_template('score/report.html')
    val1=int(request.GET['num1'])
    print(val1)
    df=(sql_value(val1)) #calling other fuction using sending id number
    #print(df)
    
    # df = pd.read_csv(r'D:\Python_Project\py\credit_analysis\credit_score\TDataset\predicted_data.csv')

    json_Value=df.to_dict(orient='records')
           
    pdf = render_to_pdf('score/report.html',{'json_Values':json_Value})
    
    if pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        filename = "Invoice_%s.pdf" %("12341231")
        content = "inline; filename='%s'" %(filename)
        download = request.GET.get("download")
        if download:
            content = "attachment; filename='%s'" %(filename)
        response['Content-Disposition'] = content
        return response
    return HttpResponse("Not found")


################################ CRUD ###############################
from score.forms import EmployeeForm  
from score.models import Employee  
from django.shortcuts import render, redirect  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'score/index.html',{'form':form})  
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"score/show.html",{'employees':employees})  
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'score/edit.html', {'employee':employee})  
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'score/edit.html', {'employee': employee})  
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  


score/templates/score/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
</head>
<body bgcolor= 'saurabh'>

{% block content %}

{% endblock  %}
    
</body>

</html>

score/templates/score/cust_id.html
{% extends 'score/base.html' %}

{% block content %}

<form action="test">
Enter the 1st number : <input type="text" name = 'num1'><br>
<input type="submit">


{% endblock %}



score/templates/score/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

score/templates/score/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

score/templates/score/messages.html
{% extends 'score/base.html' %}

{% block content %}

<h1>Our blog List </h1>
<u1>
    {% for list in blog_list %}
        <li>{{list}}</li>
    {% endfor %}
</u1>



{% endblock %}

score/templates/score/practice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hellow</title>
</head>
<body>
    <p>click here to open <a href="https://google.co.in" target="_blank" title="google page">google</a></p>
</body>
</html>

score/templates/score/result.html
{% extends 'score/base.html' %}

{% block content %}
<h4>{{result}}</h4>
{% endblock %}

score/templates/score/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  

score/templates/score/test.html
{% extends 'score/base.html' %}

{% block content %}
<h4>"Hellow world"</h4>
<table style="width:100%">
<table>
    <tr>
        <td>a</td>
        <td>b</td>
        
    </tr>

   {% for key, values in json_Value.items%}
    <tr>
        <h1><td>{{key}}</td></h1>
        <h1><td>{{values}}</td></h1>        
    </tr>
    {% endfor %} 

</table>
{% endblock %}





 {% comment %} <ul>

   <li>CREDIT SCORE:        {{json_Value.credit_numbers}}</li>
   <li>NPA:        {{json_Value.NPA}}</li>
  <li>CUSTOMER NAME:          {{json_Value.CUSTOMER_NAME}}</li>
  <li>CUSTOMER BANK NAME:     {{json_Value.CUSTOMER_BANK_NAME}}</li>
  <li>ADDRESS PROOF DETAILS:   {{json_Value.ADDRESS_PROOF_DETAILS}}</li>
   <li>KYC COMPLETE FLAG:       {{json_Value.KYC_COMPLETE_FLAG}}</li>
   <li>GST NO:                  {{json_Value.GST_NO}}</li>
   <li>GST REGISTRATION DATE:            {{json_Value.GST_REG_DATE}}</li>
   <li>PERMANENT ADDRESS:           {{json_Value.PERMANENT_ADD}}</li>
   <li>HOUSE OWN:               {{json_Value.HOUSE_OWN}}</li>
   <li>VEHICAL OWN:           {{json_Value.CAR_MOTOR_OWN}}</li>
   <li>CURRENT LIABALITY AMOUNT:           {{json_Value.CURR_LIAB_AMT}}</li>
  <li>LOAN ACCOUNT HOLD FROM MONTHS:   {{json_Value.LOAN_AC_HOLD_FRM_MTHS}}</li>
  <li>CURRENT BALANCE:             {{json_Value.CURRENT_BAL}}</li>
 <li>NEW ACCOUNT NUMBER:           {{json_Value.NEW_AC_NUMBER}}</li>
 <li>ACCOUNT OPEN DATE:       {{json_Value.ACCOUNT_OPEN_DATE}}</li>
 <li>ADDITIONAL LOAN :           {{json_Value.ADDITIONAL_YN}}</li>
 <li>AVERAGE BALANCE IN ACCOUNT:       {{json_Value.AVG_BAL_IN_ACCOUNT}}</li>
 <li>AVERAGE CREDIT IN CASH AMOUNT: {{json_Value.AVG_CR_IN_CASH_IN_AMOUNT}}</li>
 <li>AVERAGE CREDIT IN CLEARING AMOUNT:  {{json_Value.AVG_CR_IN_CLG_IN_AMOUNT}}</li>
 <li>AVERAGE CREDIT IN TRANSFER AMOUNT:  {{json_Value.AVG_CR_IN_TRF_IN_AMOUNT}}</li>
 <li>AVERAGE DEBIT IN CASH AMOUNT: {{json_Value.AVG_DR_IN_CASH_IN_AMOUNT}}</li>
 <li>AVERAGE DEBIT IN CLEARING AMOUNT:  {{json_Value.AVG_DR_IN_CLG_IN_AMOUNT}}</li>
 <li>AVERAGE DEBIT INTRANSFER AMOUNT :  {{json_Value.AVG_DR_IN_TRF_IN_AMOUNT}}</li>
 <li>CASH SECURITY FLAG:       {{json_Value.CASH_SECURITY_FLAG}}</li>
 <li>DISBURSEMENT AMOUNT:      {{json_Value.DISBURSEMENT_AMOUNT}}</li>
 <li>DP AMOUNT:                {{json_Value.DP_AMOUNT}}</li>
 <li>EMI AMOUNT:               {{json_Value.EMI_AMOUNT}}</li>
 <li>EXPIRY DATE:              {{json_Value.EXPIRY_DATE}}</li>
 <li>INTEREST RATE:            {{json_Value.INTEREST_RATE}}</li>
 <li>LAST INTREST RECEIVED AMOUNT:   {{json_Value.LAST_INTT_RECEIVED_AMT}}</li>
 <li>LAST INTREST RECEIVED DATE:    {{json_Value.LAST_INTT_RECEIVED_DT}}</li>
 <li>NET SECURITY VALUE:       {{json_Value.NET_SECURITY_VALUE}}</li>
 <li>OVERDUE AMOUNT:              {{json_Value.OVERDUE_AMT}}</li>
 <li>OVERDUE PERIOD:              {{json_Value.OVERDUE_PRD}}</li>
 <li>PENAL AMT:                {{json_Value.PENAL_AMT}}</li>
 <li>PERIOD MONTHS:            {{json_Value.PERIOD_MONTHS}}</li>
 <li>PRINCIPAL BALANCE:        {{json_Value.PRINCIPAL_BALANCE}}</li>
 <li>RECEIVABLE BALANCE:       {{json_Value.RECEIVABLE_BALANCE}}</li>
 <li>RENEWAL YN:               {{json_Value.RENEWAL_YN}}</li>
 <li>SANCTION AMOUNT:          {{json_Value.SANCTION_AMOUNT}}</li>
 <li>SANCTION DATE:            {{json_Value.SANCTION_DATE}}</li>
 <li>SECURITY VALUE:           {{json_Value.SECURITY_VALUE}}</li>
 <li>SUBSIDY APPLIED FLAG:     {{json_Value.SUBSIDY_APPLIED_FLAG}}</li>
 <li>TOTAL INTREST RECEIVED:      {{json_Value.TOTAL_INTT_RECEIVED}}</li>
 <li>TOTAL NUMBER OF TRANSFER BYATM COUNT: {{json_Value.TOTAL_NOOFTRAN_BYATM_CNT}}</li>
 <li>TOTAL NUMBER OF TRANFER BYCASH COUNT: {{json_Value.TOTAL_NOOFTRAN_BYCASH_CNT}}</li>
 <li>TOTAL NUMBER OF TRANSFER  BY CHEQUE COUNT: {{json_Value.TOTAL_NOOFTRAN_BYCHEQUE_CNT}}</li>
 <li>TOTAL NUMBER OF TRANSACTION BY CLEARING COUNT: {{json_Value.TOTAL_NOOFTRAN_BYCLG_CNT}}</li>
 <li>TOTAL NUMBER OF TRANSFER BY RTGS COUNT: {{json_Value.TOTAL_NOOFTRAN_BYRTGS_CNT}}</li>
 <li>TOTAL NOOFTRAN_BYTRF_CNT:  {{json_Value.TOTAL_NOOFTRAN_BYTRF_CNT}}</li>
 <li>TOTAL NUMBER OF CREDIT CASH TRANSFER COUNT: {{json_Value.TOTAL_NOOF_CR_CASH_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF CREDIT CLEARING TRANSFER COUNT: {{json_Value.TOTAL_NOOF_CR_CLG_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF CREDIT TRANSCATION COUNT:     {{json_Value.TOTAL_NOOF_CR_TRAN_CNT}}</li>
 <li>TOTAL NUMBER  OF CREDIT TRANSFER TRANSACTION COUNT: {{json_Value.TOTAL_NOOF_CR_TRF_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF DEBIT CASH TRANSACTION COUNT: {{json_Value.TOTAL_NOOF_DR_CASH_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF DEBIT CLEARING TRANSACTION COUNT:  {{json_Value.TOTAL_NOOF_DR_CLG_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF DEBIT TRANSACTION COUNT:      {{json_Value.TOTAL_NOOF_DR_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF DEBIT TRANSFER COUNT:  {{json_Value.TOTAL_NOOF_DR_TRF_TRAN_CNT}}</li>
 <li>TOTAL NUMBER OF TRANSFER:            {{json_Value.TOTAL_NOOF_TRAN}}</li>
 <li>VALUE DESCRIPTION:           {{json_Value.VALUE_DESCRIPTION}}</li>
 <li>AVRAGE BALANCE IN ACCOUNT SAVING ACTIVE: {{json_Value.AVG_BAL_IN_ACCOUNT_SAVING_ACTIVE}}</li>
 <li>AVRAGE BALANCE IN ACCOUNT SAVING CLOSED: {{json_Value.AVG_BAL_IN_ACCOUNT_SAVING_CLOSED}}</li>
 <li>AVRAGE BALANCE IN ACCOUNT CURRENT ACTIVE: {{json_Value.AVG_BAL_IN_ACCOUNT_CURRENT_ACTIVE}}</li>
 <li>AVRAGE BALANCE IN ACCOUNT CURRENT CLOSED: {{json_Value.AVG_BAL_IN_ACCOUNT_CURRENT_CLOSED}}</li>
 <li>BALANCE AMOUNT SAVING ACTIVE:    {{json_Value.BALANCE_AMOUNT_SAVING_ACTIVE}}</li>
 <li>BALANCE AMOUNT SAVING CLOSED:    {{json_Value.BALANCE_AMOUNT_SAVING_CLOSED}}</li>
 <li>BALANCE AMOUNT CURRENT ACTIVE:   {{json_Value.BALANCE_AMOUNT_CURRENT_ACTIVE}}</li>
 <li>BALANCE AMOUNT CURRENT CLOSED:   {{json_Value.BALANCE_AMOUNT_CURRENT_CLOSED}}</li>
 <li>TOTAL INTEREST PAID SAVING ACTIVE:   {{json_Value.TOTAL_INTT_PAID_SAVING_ACTIVE}}</li>
 <li>TOTAL INTEREST PAID SAVING CLOSED:   {{json_Value.TOTAL_INTT_PAID_SAVING_CLOSED}}</li>
 <li>TOTAL INTEREST PAID CURRENT ACTIVE:  {{json_Value.TOTAL_INTT_PAID_CURRENT_ACTIVE}}</li>
 <li>TOTAL INTEREST PAID CURRENT_CLOSED:  {{json_Value.TOTAL_INTT_PAID_CURRENT_CLOSED}}</li>
 <li>CHEQUE BOUNCE AMOUNT CURRENT AND SAVING ACCOUNT:      {{json_Value.CHEQUE_BOUNCE_AMOUNT_CASA}}</li>
 <li>CHEQUE BOUNCE CHARGES CURRENT AND SAVING ACCOUNT:     {{json_Value.CHEQUE_BOUNCE_CHARGES_CASA}}</li>
 <li>CHEQUE BOUNCE COUNT CURRENT AND SAVING ACCOUNT:         {{json_Value.CHEQUE_BOUNCE_CNT_CASA}}</li>
 <li>DEPOSIT AMOUNT FDRD ACTIVE:    {{json_Value.DEPOSIT_AMOUNT_FDRD_ACTIVE}}</li>
 <li>DEPOSIT AMOUNT FDRD CLOSED:    {{json_Value.DEPOSIT_AMOUNT_FDRD_CLOSED}}</li>
 <li>MATURITY AMOUNT FDRD ACTIVE:    {{json_Value.MATURITY_AMOUNT_FDRD_ACTIVE}}</li>
 <li>MATURITY AMOUNT FDRD ACTIVE:    {{json_Value.MATURITY_AMOUNT_FDRD_ACTIVE}}</li>
 <li>TOTAL PAYABLE INTEREST FDRD ACTIVE: {{json_Value.TOTAL_PAYABLE_INTEREST_FDRD_ACTIVE}}</li>
 <li>TOTAL PAYABLE INTEREST FDRD CLOSED: {{json_Value.TOTAL_PAYABLE_INTEREST_FDRD_CLOSED}}</li>
 <li>TOTAL NUMBER OF CREDIT TRANSFER COUNT SAVING:     {{json_Value.TOTAL_PAYABLE_INTEREST_FDRD_CLOSED}}</li>
 <li>TOTAL NUMBER OFDEBIT TRANSFER COUNT SAVING:     {{json_Value.TOTAL_NOOF_DR_TRAN_CNT_SAVING}}</li>
 <li>TOTAL NUMBER OF TRANSFER SAVING:            {{json_Value.TOTAL_NOOF_TRAN_SAVING}}</li>
 <li>TOTAL NUMBER OF CREDIT TRANSFER COUNT CURRENT:    {{json_Value.TOTAL_NOOF_CR_TRAN_CNT_CURRENT}}</li>
 <li>TOTAL NUMBER OF DEBIT TRANSFER COUNT CURRENT:    {{json_Value.TOTAL_NOOF_DR_TRAN_CNT_CURRENT}}</li>
 <li>TOTAL NUMBER OF DEBIT TRANSFER COUNT CURRENT:    {{json_Value.TOTAL_NOOF_DR_TRAN_CNT_CURRENT}}</li>
 <li>TOTAL NUMBER OF TRANSFER CURRENT:           {{json_Value.TOTAL_NOOF_TRAN_CURRENT}}</li>
 <li>TOTAL NUMBER OF ACCOUNT:               {{json_Value.TOTAL_NO_OF_ACCOUNT}}</li>
 <li>TOTAL NUMBER OF LOAN ACCOUNT:          {{json_Value.TOTAL_NO_OF_LOAN_ACCOUNT}}</li>
 <li>LOAN TYPE:                         {{json_Value.LOAN_TYPE}}</li>
 </ul>  {% endcomment %}

score/templates/score/test1.html
{% extends 'score/base.html' %}

{% block content %}

<form action="add">
Enter the 1st number : <input type="text" name = 'num1'><br>
Enter the 2nd number : <input type="text" name = 'num2'><br>
<input type="submit">

{% endblock %}
